### ISSUE TITLE
Grateful

### ISSUE THREAD

**Issue by AHStudyBank** [mauron85/react-native-background-geolocation-example#1]
Thank you so much for making this example.  However, there are many warnings.  Im working on updating them.  I am a novice and you may be able to fix them faster.  Thanks again.

**Comment by arvindkkore** [comment]
i integrate   
Error:Execution failed for task ':react-native-mauron85-background-geolocation:mergeReleaseResources'.
> Crunching Cruncher common_google_signin_btn_icon_light_focused.9.png failed

**Comment by ianaz** [comment]
Thanks also from my side. Got a small tip on Paypal :)

**Comment by mauron85** [comment]
@ianaz Thank you, really appreciate it. ;-)

**Comment by ababba15** [comment]
Hi =) What can cause this error? Can it be fixed fast?

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 41.251 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

```

**Comment by rexlow** [comment]
@ababba15 getting this aswell, +1

**Comment by ababba15** [comment]
@rexlow it magically worked, but now I can't figure out how to handle next error

`SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.`

Do you have some more magic? :D
